---
title: "Metabolics"
output: html_document
date: "2023-08-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r include=FALSE}

#removes all data from global environment
rm(list = ls())
```

```{r librarys}
library(Cardinal)
library(magick)

```

## Read data

```{r Read_data}
DATA_DIR <- "I:/CMM1636-Q5291/VLP94_MALDI/2023.09.11 imzML file/"
OUT_DIR <- "I:/GML001-Q1851/Andrew_C/Metabolomics/"

treatment_1 <- readMSIData(paste0(DATA_DIR,"vlp94c-treated-dhb.imzML"),mass.range = c(160,3000),resolution = 300, attach.only = TRUE)
control_1 <- readMSIData(paste0(DATA_DIR,"vlp94a-control-dhb.imzML"),mass.range = c(160,3000), resolution = 300, attach.only = TRUE)
treatment_2 <- readMSIData(paste0(DATA_DIR,"vlp94d-treated-dhb.imzML"),mass.range = c(160,3000), resolution = 260, attach.only = TRUE)
control_2 <- readMSIData(paste0(DATA_DIR,"vlp94b-control-dhb.imzML"),mass.range = c(160,3000), resolution = 260, attach.only = TRUE)
```



### Combine samples into treatment and control for run 1 and 2
```{r combine_runs}
set_centroid_to_true <- function(data){
  centroided(data) <- TRUE
  return(data)
}

treatment_1 <- set_centroid_to_true(treatment_1)
control_1 <- set_centroid_to_true(control_1)

### shift the coords of the treated sample so it doesnt overlap with the control sample image
treatment_1_add <- treatment_1
treatment_1_add_pixel_data <- pixelData(treatment_1_add)
treatment_1_add_pixel_data@coord$x <- treatment_1_add_pixel_data@coord$x + 200
pixelData(treatment_1_add) <- treatment_1_add_pixel_data 

treatment_2 <- set_centroid_to_true(treatment_2)
control_2 <- set_centroid_to_true(control_2)

### shift the coords of the treated sample so it doesnt overlap with the control sample image
treatment_2_add <- treatment_2
treatment_2_add_pixel_data <- pixelData(treatment_2_add)
treatment_2_add_pixel_data@coord$x <- treatment_2_add_pixel_data@coord$x + 200
pixelData(treatment_2_add) <- treatment_2_add_pixel_data 


###### Combine match runs
run1 <- Cardinal::combine(treatment_1_add, control_1)
run2 <-  Cardinal::combine(treatment_2_add, control_2)

```


## Plot Drug Data
```{r drug_data}

### Drug1
image(run1, mz=448.245, plusminus=0.01) #no features in range; re-centering m/z 448.245 to 448.260180086314
image(run1, mz=450.259, plusminus=0.01) #no features in range; re-centering m/z 450.259 to 450.281896361841

### Drug2
image(run2, mz=448.245, plusminus=0.01) #no features in range; re-centering m/z 448.245 to 448.224319843837
image(run2, mz=450.259, plusminus=0.01) #no features in range; re-centering m/z 450.259 to 450.209856151453
```


## Normalise data
```{r normalise_data}

mse_normlisation <- function(data){
  new_data <- normalize(data, method="rms")
  
  return(new_data)
}


run1_pre <- mse_normlisation(run1)
run2_pre <- mse_normlisation(run2)


mse_process <- function(data){
  new_data <- process(data)
  return(new_data)
}

run1_pre <- mse_process(run1_pre)
run2_pre <- mse_process(run2_pre)

saveRDS(run1_pre, "I:/GML001-Q1851/Andrew_C/Metabolomics/normalised_run1_pre.RDS")
saveRDS(run2_pre, "I:/GML001-Q1851/Andrew_C/Metabolomics/normalised_run2_pre.RDS")
```


## Plot Normalised Drug Data
```{r normalised_drug_data}

### Drug1
image(run1_pre, mz=448.245, plusminus=0.01) #no features in range; re-centering m/z 448.245 to 448.260180086314
image(run1_pre, mz=450.259, plusminus=0.01) #no features in range; re-centering m/z 450.259 to 450.281896361841

### Drug2
image(run2_pre, mz=448.245, plusminus=0.01) #no features in range; re-centering m/z 448.245 to 448.224319843837
image(run2_pre, mz=450.259, plusminus=0.01) #no features in range; re-centering m/z 450.259 to 450.209856151453
```



## Plot important metabolites
```{r plot_metabolites}

important_metabolomics <- read.csv(paste0(OUT_DIR, "Important_metabolites.csv"))
FMP10_detected <- read.csv(paste0(OUT_DIR, "FMP10_detected.csv"))
DHB_detected <- read.csv(paste0(OUT_DIR, "DHB_detected.csv"))



plot_metabolite <- function(met_dir, run_sub, pdf_name, run_name, metabolite, mz){
  
  
  if (run_sub == "run1_pre"){
    if (run_name == "1-1-visium-dhb-control"){
      plot <- Cardinal::image(run1_pre, mz = mz, subset= run(run1_pre) == "1-1-visium-dhb-control")
    } else{
       plot <- Cardinal::image(run1_pre, mz = mz, subset= run(run1_pre) == "1-1-visium-dhb-treated")
    }
  } else{
     if (run_name == "2-1-visium-dhb-control"){
       plot <- Cardinal::image(run2_pre, mz = mz, subset= run(run2_pre) == "2-1-visium-dhb-control")
    } else{
       plot <- Cardinal::image(run2_pre, mz = mz, subset= run(run2_pre) == "2-1-visium-dhb-treated")
    }
  }
  
  plot_name <- paste0(met_dir,metabolite,pdf_name, ".jpeg")
  jpeg(plot_name)
  plot
  dev.off()
  
}


already_mapped <- c()
#important_metabolites
idx <- 1
while(idx <= length(important_metabolomics$Compound.name)){
  if (important_metabolomics$Monoisotopic.neutral.mass[idx] > 160){
    metabolite_name <- important_metabolomics$Compound.name[idx]
    if (metabolite_name %in% already_mapped){
      metabolite_name <- paste0(metabolite_name,".1")
    }
    
    met_dir <- paste0(wd,metabolite_name, "/")
    dir.create(met_dir)
    
    #control_1
    plot_metabolite(met_dir = met_dir, run_sub = "run1_pre", 
                    pdf_name = "_control_1", run_name = "1-1-visium-dhb-control", 
                    metabolite = metabolite_name, mz = important_metabolomics$Monoisotopic.neutral.mass[idx])
    
    #treatment_1
    plot_metabolite(met_dir = met_dir,run_sub = "run1_pre", 
                    pdf_name = "_treatment_1", run_name = "1-1-visium-dhb-treated", 
                    metabolite = metabolite_name, mz = important_metabolomics$Monoisotopic.neutral.mass[idx])
  
    #control_2
    plot_metabolite(met_dir = met_dir,run_sub = "run2_pre", 
                    pdf_name = "_control_2", run_name = "2-1-visium-dhb-control", 
                    metabolite = metabolite_name, mz = important_metabolomics$Monoisotopic.neutral.mass[idx])
  
    #treatment_2
    plot_metabolite(met_dir = met_dir,run_sub = "run2_pre", 
                    pdf_name = "_treatment_2", run_name = "2-1-visium-dhb-treated", 
                    metabolite = metabolite_name, mz = important_metabolomics$Monoisotopic.neutral.mass[idx])
    
   
    already_mapped <- c(already_mapped,metabolite_name)
  }
  idx <- idx+1
}




```







```{r}
treatment_1_1 %>% subsetPixels(x==100, y==100, run=="1-1-visium-dhb-treated") %>%
    process() %>%
    peakPick(method="mad") %>%
    process(plot=TRUE, par=list(main="MAD noise", layout=c(3,1)))

treatment_1_1 %>% subsetPixels(x==100, y==100, run=="1-1-visium-dhb-treated") %>%
    process() %>%
    peakPick(method="simple") %>%
    process(plot=TRUE,
            par=list(main="Simple SD noise"))

treatment_1_1 %>% subsetPixels(x==100, y==100, run=="1-1-visium-dhb-treated") %>%
    process() %>%
    peakPick(method="adaptive") %>%
    process(plot=TRUE, par=list(main="Adaptive SD noise"))
```







