---
title: "CervicalCancerRefData"
author: "Andrew Causer"
date: "2023-08-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r clear_environment}
rm(list = ls())
```

```{r packages, warning=FALSE}
library(Matrix)
library(Seurat)
library(SeuratObject)
library(dplyr)
library(ggplot2)
library(gridExtra)
```


```{r inport_data}
#our data

read_Old_10X_Spatial <- function (path, sample){
  
  image <- Read10X_Image(paste0(DATA_DIR,"/",sample,"/outs/spatial/"))
  counts <- Read10X_h5(filename = paste0(DATA_DIR,"/",sample,"/outs/filtered_feature_bc_matrix.h5"))
  
  data <- CreateSeuratObject(counts = counts, assay = "Spatial")
  
  data@images$slice1 <- image
  
return(data)
  
}


DATA_DIR <- "I:/GML001-Q1851/Andrew_C/CIN/CIN_data"


#Inport data from GSE208653_RAW

data_path <- "I:/GML001-Q1851/Andrew_C/CIN/"

x <-read.table(paste0(data_path,"sample1barcodes.tsv.gz"))
y <- read.table(paste0(data_path,"sample1features.tsv.gz"))
z <- readMM(paste0(data_path,"sample1matrix.mtx.gz"))
  
```

```{r image_int_vals}
#Some of the images are inporting with non-int values, this code fixes that

image_to_int <- function(seurat_obj){
  seurat_obj@images[["slice1"]]@coordinates[["tissue"]] <- as.integer(seurat_obj@images[["slice1"]]@coordinates[["tissue"]])
  seurat_obj@images[["slice1"]]@coordinates[["row"]] <- as.integer(seurat_obj@images[["slice1"]]@coordinates[["row"]])
  seurat_obj@images[["slice1"]]@coordinates[["col"]] <- as.integer(seurat_obj@images[["slice1"]]@coordinates[["col"]])
  seurat_obj@images[["slice1"]]@coordinates[["imagerow"]] <- as.integer(seurat_obj@images[["slice1"]]@coordinates[["imagerow"]])
  seurat_obj@images[["slice1"]]@coordinates[["imagecol"]] <- as.integer(seurat_obj@images[["slice1"]]@coordinates[["imagecol"]])
  
  return(seurat_obj)
  
}
```


```{r}
data_names <- c("VLP85_A","VLP85_D","VLP86_A","VLP86_D","VLP89_A","VLP89_D","VLP90_A","VLP90_D")

# generate a list of objects 

data_list <- list()

for (sample in data_names){
  data <- read_Old_10X_Spatial(DATA_DIR,sample)
  data_list[[sample]] <- image_to_int(data)
  
}
```


```{r}

qc_plots <- function(seurat_obj){
  plot1 <- SpatialFeaturePlot(seurat_obj, features = "nCount_Spatial")
  plot2 <- SpatialFeaturePlot(seurat_obj, features = "nFeature_Spatial") + theme(legend.position = "right")
  plot1+plot2
}

for (sample in names(data_list)){
  print(qc_plots(data_list[[sample]]))
}

```


```{r}

for (sample in data_list){
  print(SpatialFeaturePlot(sample, features = c("IL34","CSF1")))
}


```





```{r run_qc}
run_qc <- function(data, min_genes, min_spots, assay="RNA") {
    
    dim(data@meta.data)
    head(data@meta.data)
    
    # QC - removing Mitochondrial and Ribosomal Genes
    print("QC - removing Mitochondrial and Ribosomal Genes...")
    data <- PercentageFeatureSet(data, "^MT-", col.name = "percent_mito", assay=assay)
    data <- PercentageFeatureSet(data, "^RP[SL]", col.name = "percent_ribo", assay=assay)

    ## check the feature and count distribution before qc
    feats <- c("nFeature_Spatial", "nCount_Spatial")
        
    # filtering 
    selected_c <- WhichCells(data, expression = nFeature_Spatial > min_genes)
    length(selected_c)
    
    selected_f <- rownames(data)[Matrix::rowSums(data) > min_spots]
    length(selected_f)
    
    data <- subset(data, features = selected_f, cells = selected_c)
    
    selected_c2=rownames(data@meta.data)[data$orig.ident!='']
    data <- subset(data,  cells = selected_c2)
    print("Keeping the filtered spots in Seurat object...")
    
    return(data)
}


```

```{r run_qc_data}
data_list_qc <-c()
for (sample in data_list){
  d <- run_qc(sample, min_genes = 10, min_spots = 3, assay = "Spatial")
  data_list_qc <- c(data_list_qc, d)
}
```

```{r generate_clusters}
data_list_umaps <- c()

for (sample in data_list_qc){
  d <- SCTransform(sample, assay = "Spatial", verbose = FALSE)
  d <- RunPCA(d, assay = "SCT", verbose = FALSE)
  d <- FindNeighbors(d, reduction = "pca", dims = 1:30)
  d <- FindClusters(d, resolution = 0.5,verbose = FALSE)
  d <- RunUMAP(d, reduction = "pca", dims = 1:30)
  data_list_umaps <- c(data_list_umaps, d)
}

```


```{r plot_clusters}
for (sample in data_list_umaps[]){
  print(SpatialDimPlot(sample))
}
```

```{r}

outdir <- "~/Documents/Work/CIN3/FindAllMarkers/"
dir.create(outdir)


idx <- 1
top_10 <-c()

while(idx <= length(data_list_umaps[])){
  sample <- data_list_umaps[[idx]]
  markers <- FindAllMarkers(sample, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
  markers <- markers %>% dplyr::filter(p_val_adj <= 0.05)
  markers <- markers %>% group_by(cluster) %>% arrange(-avg_log2FC) %>% dplyr::slice(1:50)
  top10_norm <- markers %>% group_by(cluster) %>% arrange(-avg_log2FC) %>% dplyr::slice(1:10)
  top_10 <- c(top_10, list(top10_norm))
  write.table(markers, file = paste0(outdir, data_list_names[idx], "_allmarkers.txt"), sep = "\t", quote = FALSE, col.names = NA)
  idx <- idx + 1
}
```


```{r rename_ids}
VLP85_A_clusters <- c(
  "0" = "Endothelial Cells",
  "1" = "Myofibroblasts",
  "2" = "Fibroblasts",
  "3" = "Smooth Muscle Cells",
  "4" = "Secretory Epithelial Cells",
  "5" = "Epithelial Cells",
  "6" = "Secretory Epithelial Cells",
  "7" = "Epithelial Cells",
  "8" = "Keratinocytes"
)

VLP85_D_clusters <- c(
  "0" = "Smooth Muscle Cells",
  "1" = "Smooth Muscle Cells",
  "2" = "Smooth Muscle Cells",
  "3" = "Endothelial Cells",
  "4" = "Epithelial Cells",
  "5" = "Endothelial Cells",
  "6" = "B Cells",
  "7" = "Fibroblasts",
  "8" = "Fibroblasts",
  "9" = "Secretory Epithelial Cells",
  "10" = "Keratinocytes"
)

VLP86_A_clusters <- c(
  "0" = "Endothelial Cells",
  "1" = "Smooth Muscle Cells",
  "2" = "Secretory Epithelial Cells",
  "3" = "Secretory Epithelial Cells",
  "4" = "Keratinocytes",
  "5" = "Endothelial Cells",
  "6" = "Smooth Muscle Cells",
  "7" = "Schwann Cells",
  "8" = "Plasma Cells",
  "9" = "Macrophages",
  "10" = "Endothelial Cells",
  "11" = "Secretory Epithelial Cells",
  "12" = "Schwann Cells"
)

VLP86_D_clusters <- c(
  "0" = "Smooth Muscle Cells",
  "1" = "Secretory Epithelial Cells",
  "2" = "B Cells",
  "3" = "Fibroblasts",
  "4" = "Myofibroblasts",
  "5" = "Secretory Epithelial Cells",
  "6" = "Smooth Muscle Cells",
  "7" = "Secretory Epithelial Cells",
  "8" = "Keratinocytes"
)

VLP89_A_clusters <- c(
  "0" = "Myofibroblasts",
  "1" = "Endothelial Cells",
  "2" = "Fibroblasts",
  "3" = "B Cells",
  "4" = "Secretory Epithelial Cells",
  "5" = "Secretory Epithelial Cells",
  "6" = "Smooth Muscle Cells",
  "7" = "Keratinocytes",
  "8" = "Smooth Muscle Cells",
  "9" = "Monocytes",
  "10" = "Unknown Cell Type",
  "11" = "Myofibroblasts"
)

VLP89_D_clusters <- c(
  "0" = "Myofibroblasts",
  "1" = "B Cells",
  "2" = "Secretory Epithelial Cells",
  "3" = "Macrophages",
  "4" = "Uknown Cell Type",
  "5" = "Smooth Muscle Cells",
  "6" = "Keratinocytes",
  "7" = "Epithelial Cells",
  "8" = "Secretory Epithelial Cells",
  "9" = "Smooth Muscle Cells"
)

VLP90_A_clusters <- c(
  "0" = "Smooth Muscle Cells",
  "1" = "Secretory Epithelial Cells",
  "2" = "Smooth Muscle Cells",
  "3" = "Fibroblasts",
  "4" = "Secretory Epithelial Cells",
  "5" = "Keratinocytes",
  "6" = "Endothelial Cells",
  "7" = "Smooth Muscle Cells",
  "8" = "Secretory Epithelial Cells",
  "9" = "Fibroblasts",
  "10" = "B Cells",
  "11" = "Keratinocytes"
)

VLP90_D_clusters <- c(
  "0" = "Smooth Muscle Cells",
  "1" = "Secretory Epithelial Cells",
  "2" = "Unknown Cell Type",
  "3" = "Fibroblasts",
  "4" = "Smooth Muscle Cells"
)

cell_annot_list <-list(VLP85_A_clusters, VLP85_D_clusters,VLP86_A_clusters,VLP86_D_clusters, VLP89_A_clusters, VLP89_D_clusters, VLP90_A_clusters, VLP90_D_clusters)


idx <- 1 
data_ident_rename <- c()
while (idx <= length(data_list_umaps[])){
  sample_x <- RenameIdents(data_list_umaps[[idx]], cell_annot_list[[idx]])
  data_ident_rename <- c(data_ident_rename, sample_x)
  idx <- idx+1
}


```


```{r}
for (sample in data_list_umaps[]){
  print(SpatialDimPlot(sample, label = TRUE))
}
```


```{r Genes_of_interest}
for (sample in data_list_umaps[]){
  print(SpatialFeaturePlot(sample, slot = "scale.data", features = c("IL34","CSF1","CDKN2A")))
}
```


```{r plot_epi_marker_genes}
for (sample in data_list_umaps[]){
  print(SpatialFeaturePlot(sample, features = c("KRT13","CDKN2A","CD24","CDH1","PECAM1","CDH5","IL33", "KRT18",), ncol = 5))
}
```



```{r gene_heat_map}

##### GENES FROM ENRICR and doi: 10.3389/fimmu.2022.966291

feature_list <- c("EHF","CDKN2A","EPCAM", #Epithelial
                  "PECAM1","ENG", #Endothelial Cells
                  "MUC1", #Goblet Cells
                  "KRT5","KRT15","KRT16", #Keratinocytes
                  "CD14",#"CD86, NCF2", #Macrophage
                  "FN1","VIM", "COL14A1", "TAGLN", #Fibroblast
                  "MYLK","ACTG2", # Smooth Muscle
                  "CD79A","CD79B", #B Cells
                  "IL34","CSF1",#Genes of Interest
                  "CDKN2B","TOX3","ANLN","BAG1","MUC16","KMT2C" # Cervical Cancer Genes
                  )


for (sample in data_ident_rename[]){
  
  df <- AverageExpression(sample, assays = "SCT",features = feature_list, slot = "count")
  df <- as.matrix(df$SCT)

  annot_row<- data.frame(Group  = factor(rep(c("Epithelial","Endothelial","Goblet Cells","Keratinocytes","Macrophages","Fibroblast","Smooth Muscle","B Cells","Genes of Interest","Cervical Cancer Genes"), c(3,2,1,3,1,4,2,2,2,6))))
  rownames(annot_row) <- rownames(df)

  gaps<- c(3,5,6,9,10,14,16,18,20)


  print(pheatmap(df, cluster_cols = FALSE, cluster_rows = FALSE, scale = "row", annotation_row = annot_row, gaps_row = gaps))

}



```


```{r}

##### Reformats the gene names, and selects unique marker genes for each cell type annotation per sample


V85_A_R <- read.csv("~/Documents/Work/CIN3/FindAllMarkers/VLP85_A_EnrichR.csv",header = TRUE)
V85_D_R <- read.csv("~/Documents/Work/CIN3/FindAllMarkers/VLP85_D_EnrichR.csv",header = TRUE)
V86_A_R <- read.csv("~/Documents/Work/CIN3/FindAllMarkers/VLP86_A_EnrichR.csv",header = FALSE)
V86_D_R <- read.csv("~/Documents/Work/CIN3/FindAllMarkers/VLP86_D_EnrichR.csv",header = FALSE)
V89_A_R <- read.csv("~/Documents/Work/CIN3/FindAllMarkers/VLP89_A_EnrichR.csv",header = FALSE)
V89_D_R <- read.csv("~/Documents/Work/CIN3/FindAllMarkers/VLP89_D_EnrichR.csv",header = FALSE)
V90_A_R <- read.csv("~/Documents/Work/CIN3/FindAllMarkers/VLP90_A_EnrichR.csv",header = FALSE)
V90_D_R <- read.csv("~/Documents/Work/CIN3/FindAllMarkers/VLP90_D_EnrichR.csv",header = FALSE)


VLP85_A_EnrichR <- V85_A_R
for(column in colnames(V85_A_R)){
  gene_list <- unique(V85_A_R[column])
  if(length(gene_list) != dim(V85_A_R)[1]){
    gene_list <-c(unlist(gene_list),rep(c("NA"),(dim(V85_A_R)[1]-length(unlist(gene_list)))))
    print(gene_list)
    VLP85_A_EnrichR[column] <- gene_list
  }
}

VLP85_D_EnrichR <- V85_D_R
for(column in colnames(V85_D_R)){
  gene_list <- unique(V85_D_R[column])
  if(length(gene_list) != dim(V85_D_R)[1]){
    gene_list <-c(unlist(gene_list),rep(c("NA"),(dim(V85_D_R)[1]-length(unlist(gene_list)))))
    print(gene_list)
    VLP85_D_EnrichR[column] <- gene_list
  }
}


V86_A_R <- V86_A_R[1:(length(unique(V86_A_R$V1))-1),]
rownames(V86_A_R) <- V86_A_R$V1
V86_A_R <- V86_A_R[,-1]

VLP86_A_EnrichR <- data.frame(matrix(nrow = 50, ncol = 0))
for(row in rownames(V86_A_R)){
  genes <- unique(strsplit((V86_A_R[row,]$V2),";")[[1]])
  genes <- c(genes, rep(c(""),(50-length(genes))))
  VLP86_A_EnrichR[row] <- genes
}



V86_D_R <- V86_D_R[1:(length(unique(V86_D_R$V1))-1),]
rownames(V86_D_R) <- V86_D_R$V1
V86_D_R <- V86_D_R[,-1]

VLP86_D_EnrichR <- data.frame(matrix(nrow = 50, ncol = 0))
for(row in rownames(V86_D_R)){
  genes <- unique(strsplit((V86_D_R[row,]$V2),";")[[1]])
  genes <- c(genes, rep(c(""),(50-length(genes))))
  VLP86_D_EnrichR[row] <- genes
}



V89_A_R <- V89_A_R[1:(length(unique(V89_A_R$V1))-1),]
rownames(V89_A_R) <- V89_A_R$V1
V89_A_R <- V89_A_R[,-1]

VLP89_A_EnrichR <- data.frame(matrix(nrow = 50, ncol = 0))
for(row in rownames(V89_A_R)){
  genes <- unique(strsplit((V89_A_R[row,]$V2),";")[[1]])
  genes <- c(genes, rep(c(""),(50-length(genes))))
  VLP89_A_EnrichR[row] <- genes
}



V89_D_R <- V89_D_R[1:(length(unique(V89_D_R$V1))-1),]
rownames(V89_D_R) <- V89_D_R$V1
V89_D_R <- V89_D_R[,-1]

VLP89_D_EnrichR <- data.frame(matrix(nrow = 50, ncol = 0))
for(row in rownames(V89_D_R)){
  genes <- unique(strsplit((V89_D_R[row,]$V2),";")[[1]])
  genes <- c(genes, rep(c(""),(50-length(genes))))
  VLP89_D_EnrichR[row] <- genes
}



V90_A_R <- V90_A_R[1:(length(unique(V90_A_R$V1))-1),]
rownames(V90_A_R) <- V90_A_R$V1
V90_A_R <- V90_A_R[,-1]

VLP90_A_EnrichR <- data.frame(matrix(nrow = 50, ncol = 0))
for(row in rownames(V90_A_R)){
  genes <- unique(strsplit((V90_A_R[row,]$V2),";")[[1]])
  genes <- c(genes, rep(c(""),(50-length(genes))))
  VLP90_A_EnrichR[row] <- genes
}



V90_D_R <- V90_D_R[1:(length(unique(V90_D_R$V1))-1),]
rownames(V90_D_R) <- V90_D_R$V1
V90_D_R <- V90_D_R[,-1]

VLP90_D_EnrichR <- data.frame(matrix(nrow = 50, ncol = 0))
for(row in rownames(V90_D_R)){
  genes <- unique(strsplit((V90_D_R[row,]$V2),";")[[1]])
  genes <- c(genes, rep(c(""),(50-length(genes))))
  VLP90_D_EnrichR[row] <- genes
}

outdir <- "~/Documents/Work/CIN3/FindAllMarkers/unique_enrichr_markers/"
dir.create(outdir)

write.csv(VLP85_A_EnrichR,paste0(outdir, "VLP85_A_EnrichR_markers.csv"))
write.csv(VLP85_D_EnrichR,paste0(outdir, "VLP85_D_EnrichR_markers.csv"))
write.csv(VLP86_A_EnrichR,paste0(outdir, "VLP86_A_EnrichR_markers.csv"))
write.csv(VLP86_D_EnrichR,paste0(outdir, "VLP86_D_EnrichR_markers.csv"))
write.csv(VLP89_A_EnrichR,paste0(outdir, "VLP89_A_EnrichR_markers.csv"))
write.csv(VLP89_D_EnrichR,paste0(outdir, "VLP89_D_EnrichR_markers.csv"))
write.csv(VLP90_A_EnrichR,paste0(outdir, "VLP90_A_EnrichR_markers.csv"))
write.csv(VLP90_D_EnrichR,paste0(outdir, "VLP90_D_EnrichR_markers.csv"))





```



```{r}

marker_gene_list <-list(VLP85_A_EnrichR,VLP85_D_EnrichR,VLP86_A_EnrichR,VLP86_D_EnrichR,VLP89_A_EnrichR,VLP89_D_EnrichR,VLP90_A_EnrichR,VLP90_D_EnrichR)

idx <- 1
while (idx <= length(data_ident_rename[])){
  for (cell_type in colnames(marker_gene_list[[idx]])){
    print(VlnPlot(data_ident_rename[[idx]], slot = "count",features = marker_gene_list[[idx]][,cell_type],stack = TRUE)+ggtitle(paste0(data_list_names[idx],"_",cell_type))+NoLegend())
  }
  idx <- idx +1
}


```


```{r}

IL34.CSF1_list <- list()

for (sample in data_list_qc[]){
  ex <- log(FetchData(sample, vars = "IL34") * FetchData(sample, vars = "CSF1"))
  colnames(ex)[1] <- "IL34.CSF1"
  obj <- AddMetaData(sample,ex)
  IL34.CSF1_list <- c(IL34.CSF1_list, obj)
}

```


```{r}
for (sample in IL34.CSF1_list[]){
 print(SpatialFeaturePlot(sample, features = "IL34.CSF1" )) 
}
```








```{r}
#uses normalised

features_to_plot <-c("IL34","CSF1","CSF1R",
                     "CDKN2A","CD14","CTLA-4")

for (sample in data_list_umaps[]){
  print(SpatialFeaturePlot(sample, slot = "count", features = features_to_plot,ncol = 3))
}
```



```{r}
#uses normalised

features_to_plot <-c("CD4","FOXP3", "CD80", "CD86", "CD163",
                     "CD207", "CD1A")

for (sample in data_list_qc[]){
  print(SpatialFeaturePlot(sample, slot = "count", features = features_to_plot,ncol = 3))
}
```




```{r generate_CIM3_feature_plots}

Generate_plots <- function(seurat_obj, features){
  SpatialFeaturePlot(seurat_obj, features = c(features))
}

features_to_plot <- c("IL34", "CSF1")

Generate_plots(VLP85_A, features_to_plot)
Generate_plots(VLP85_D, features_to_plot)
Generate_plots(VLP86_A, features_to_plot)
Generate_plots(VLP86_D, features_to_plot)
Generate_plots(VLP89_A, features_to_plot)
Generate_plots(VLP89_D, features_to_plot)
Generate_plots(VLP90_A, features_to_plot)
Generate_plots(VLP90_D, features_to_plot)

```


```{r}
library("cellxgene.census")

census <- open_soma()

organism <-  "Homo sapiens"
tissue_type <- "tissue == 'uterine cervix'"
cell_columns <-  c("assay", "cell_type", "tissue", "tissue_general", "suspension_type", "disease")

seurat_obj <-  get_seurat(
   census = census,
   organism = organism,
   obs_value_filter = tissue_type,
   obs_column_names = cell_columns
)

so <- NormalizeData(seurat_obj, normalization.method = "LogNormalize", scale.factor = 10000)
so <- FindVariableFeatures(so, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(so)
so <- ScaleData(so, features = all.genes)
so <- RunPCA(so, features = VariableFeatures(object = so))
so <- FindNeighbors(so, dims = 1:10)
so <- FindClusters(so, resolution = 0.5)
so <- RunUMAP(so, dims = 1:10)
DimPlot(so, reduction = "umap")


sort(table(so@meta.data$cell_type))




```













```{r inport data}

inport_data_export_Seurat <- function(barcodes, features, count_mtx){
  
  ########
  # Inputs: 
  #   barcode_data: a filepath indicate the .barcodes.tsv.gz file for sample X
  #   feature_data: a filepath indicate the .features.tsv.gz file for sample X
  #   count_data: a filepath indicate the .matrix.mtx.gz file for sample X
  #
  # Returns:
  #   A Seurat object with the count data of sample X
  ########
  
  #if (dim(count_mtx)[1] != dim(features[1]) | dim(count_mtx)[2] != dim(barcodes[1])){
  #  print("THERE IS AN ERROR ------> The number of genes or number of barcodes does not match the data matrix dims")
  #}
  count_df <- as.data.frame(count_mtx)
  colnames(count_df) <- barcodes$V1
  
  # adds ".1" to any gene that has a replicated gene name
  unique_genes <- c()
  non_unique_list <-c()
  for(gene in features$V2){
    if (!(gene %in% unique_genes)){
      unique_genes <- c(unique_genes,gene)
      non_unique_list <-c(non_unique_list,gene)
    } else{
      non_unique_list <- c(non_unique_list,paste0(gene,".1"))
    }
  }
  
  rownames(count_df) <- non_unique_list #Get the gene names
  seurat_obj <- CreateSeuratObject(counts = count_df)
  return(seurat_obj)

}

```






```{r in}

obj1 <- inport_data_export_Seurat(x,y,z)

```


```{r}

obj1[["percent.mt"]] <- PercentageFeatureSet(obj1, pattern = "^MT-")

count.max <- round(mean(obj1$nCount_RNA) + 2 * sd(obj1$nCount_RNA), digits = -2)
count.min <- round(mean(obj1$nCount_RNA) - 2 * sd(obj1$nCount_RNA), digits = -2)
feat.max <- round(mean(obj1$nFeature_RNA) + 2 * sd(obj1$nFeature_RNA), digits = -2)
feat.min <- round(mean(obj1$nFeature_RNA) - 2 * sd(obj1$nFeature_RNA), digits = -2)

## Set minimum parameters to 0 if negative value
if (count.min < 0){
   count.min <- 0
} else {
   count.min <- count.min
}
  
if (feat.min < 0){
   feat.min <- 0
} else {
   feat.min <- feat.min
}

## Filter cells
so <- subset(obj1, subset = nFeature_RNA > feat.min & nFeature_RNA < feat.max & nCount_RNA < count.max & nCount_RNA > count.min & percent.mt < 10)
```

```{r}
so <- NormalizeData(so, normalization.method = "LogNormalize", scale.factor = 10000)
so <- FindVariableFeatures(so, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(so)
so <- ScaleData(so, features = all.genes)
so <- RunPCA(so, features = VariableFeatures(object = so))
so <- FindNeighbors(so, dims = 1:10)
so <- FindClusters(so, resolution = 0.5)
so <- RunUMAP(so, dims = 1:10)
DimPlot(so, reduction = "umap")
```



```{r}

red <- 1 / (1 + exp(x = -(1:10 - 0.5 * 10) / 0.9))
green <- 1 / (1 + exp(x = -(1:10 - 0.5 * 10) / 0.9))
blue <- 0.2
alpha <- lapply(X = list(red, green, blue), FUN = '^', 40)
alpha <- Reduce(f = '+', x = alpha)
alpha <- 0.99 - 0.1 * exp(x = -alpha / 1)
rgb(red = red, green = green, blue = blue, alpha = alpha)
 
```
















